### ISSUE TITLE
add requirements.txt so pyBadlands can be installed from source

### ISSUE THREAD

**Issue by yochannah** [badlands-model/pyBadlands#10]
Hiya! 

I was trying to download and run pyBadlands, but right now it looks like the documentation just points to the dockerfiles. It would be nice to have an easier way to install dependencies :)

**Comment by tristan-salles** [comment]
There is a user documentation available from the workshop repo:
https://github.com/badlands-model/pyBadlands-workshop

The best and easiest way to use badlands without having to go through the pain of installing all the dependencies is to use the docker environment. There is in page 32 of the user documentation on how to install and use it. It's pretty simple. 

If you are willing to install the code on your local environment, there are a bit more steps involved but you can find some info about it on the wiki page:
https://github.com/badlands-model/pyBadlands/wiki

Hope it helps!

Tristan

**Comment by yochannah** [comment]
The wiki page was what I was looking for - thanks!
