### ISSUE TITLE
Occasional segfaults in delaunay_voronoi_duality

### ISSUE THREAD

**Issue by ihowson** [badlands-model/pyBadlands#2]
Appears about 1/16 of the time on Artemis (HRtest example), 1/3 of the time on OS X (Delta example). Not seeing it on flexure.

```
Thread 1 received signal SIGSEGV, Segmentation fault.
delaunay_voronoi_duality (overon=.TRUE.) at FVclass.f90:765
765	                 voronoi_area(cell)=voronoi_area(cell)+0.5*abs(area)
```

**Comment by tristan-salles** [comment]
Is the area a Nan value or the cell Id negative or greater than allocate number?

Sent from my iPhone

On 22 Jul 2016, at 15:40, Ian Howson <notifications@github.com<mailto:notifications@github.com>> wrote:


Appears about 1/16 of the time on Artemis (HRtest example), 1/3 of the time on OS X (Delta example).

Thread 1 received signal SIGSEGV, Segmentation fault.
delaunay_voronoi_duality (overon=.TRUE.) at FVclass.f90:765
765                  voronoi_area(cell)=voronoi_area(cell)+0.5*abs(area)

**Comment by ihowson** [comment]
Cell id is 1 but ```voronoi_border``` and a few others do not seem to be allocated. Still investigating.

**Comment by ihowson** [comment]
I can't reproduce this any more.

**Comment by tristan-salles** [comment]
+1 !

—
Tristan Salles
tristan.salles@sydney.edu.au<mailto:tristan.salles@sydney.edu.au>
  (w)  +61 2 8627 4123
  (m)  +61 4 5146 2502
usyd-profile<http://sydney.edu.au/science/people/tristan.salles.php>  | badlands<http://github.com/badlands-model>


On 22 August 2016 at 5:00:04 PM, Ian Howson (notifications@github.com<mailto:notifications@github.com>) wrote:

I can't reproduce this any more.
